{
  "id": "/questions/20876028",
  "creationDate": "2014-01-04T19:46:17.770",
  "body": "\n\nI have the following method that raise exception:\n\n\t@ApiMethod(name = \"login\")\n\tpublic Profile getLogin(User user) throws UnauthorizedException {\n\t\n\t    if (user == null){\n\t        throw new UnauthorizedException(\"missing user\");\n\t    }\n\t\n\t    ...\n\t}\n\t\n\nHow to catch the error in android client AsyncTask?\n\n\tprotected Profile doInBackground(Void... unused) {\n\t\n\t    Profile profile = null;\n\t    try {\n\t        profile = service.login().execute();\n\t\n\t    } catch (Exception e) {\n\t        Log.d(\"exception\", e.getMessage(), e);\n\t    }\n\t\n\t    return profile;\n\t}\n\t\n\nThe above didn't catch the UnauthorizedException.",
  "lastActivityDate": "2014-08-11T05:42:56.211",
  "title": "Google Cloud Endpoints Custom Exception",
  "tags": [
    "java",
    "android",
    "exception",
    "google-cloud-endpoints"
  ],
  "docScore": 0,
  "comments": [],
  "answers": [],
  "creationYearMonth": "201408",
  "itemTally": 0,
  "owner": {
    "displayName": "JR Galia",
    "id": "851029"
  }
}